root = "."
tmp_dir = "logs"

[build]
  bin = "bin/sandra-alianza"
  cmd = "make"
  exclude_dir = ["assets", "tmp", "vendor", "tests", "bin"]
  exclude_regex = ["_test.go", "_templ.go"]
  include_ext = ["go", "templ", "env"]
  include_file = []
  log = "logs/air.log"
  stop_on_error = true

[color]
  app = "red"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false

[misc]
  clean_on_exit = true
