APP_NAME = sandra-alianza

BIN_DIR = bin
SRC_DIR = cmd
TEST_DIR = test

MAIN_FILE = $(SRC_DIR)/main.go
EXEC_FILE = $(BIN_DIR)/$(APP_NAME)

TEMPLATES_DIR = templates
# THESE ARE THE FILES GENERATED BY TEMPLATES THAT NEED TO BE REMOVED BEFORE REGENERATING
TEMP_FILES += $(wildcard $(TEMPLATES_DIR)/*_templ.go)
TEMP_FILES += $(wildcard $(TEMPLATES_DIR)/*_templ.txt)

.PHONY: templates all tailwind

all: templates tailwind
	@go build -o $(EXEC_FILE) $(MAIN_FILE)

templates:
	@echo "Deleting old templates"
	@rm -f $(TEMP_FILES)
	@echo "Generating templates"
	@templ generate


TAILWIND_DIR = ./static/styles

tailwind:
	@echo "Generating tailwind css"
	@npx tailwindcss -i $(TAILWIND_DIR)/input.css -o $(TAILWIND_DIR)/output.css


# # the next line is used for getting a proxy so you can reload the page when saving a file, kinda like vite
# serve:
# 	@templ generate --watch --proxy="http://localhost:8080" --open-browser=true

.PHONY: run again clean test
again: clean all run
test:
	@go test -v $(TEST_DIR)/...
run:
	@./$(EXEC_FILE)
clean:
	@rm -rf $(EXEC_FILE)
